/*
 * This source file was generated by the Gradle 'init' task
 */
package org.primaryprograms.app;

public class MessageUtils {
    private MessageUtils(){
        
    }
    private static final String MESSAGE = "Hello World!";
    public static String getMessage() {
        return MESSAGE;
    }
}
